
### Create article(AUTHOR)
POST http://localhost:4000/author-api/article
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18zOHFQUlJ1b014RGJPWXdNZjJ1blZNYmhBcjQiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjUxNzMiLCJleHAiOjE3Njk2OTY4NDUsImZ2YSI6WzAsLTFdLCJpYXQiOjE3Njk2OTY3ODUsImlzcyI6Imh0dHBzOi8vcHJvbW90ZWQtZG9lLTQ4LmNsZXJrLmFjY291bnRzLmRldiIsIm5iZiI6MTc2OTY5Njc3NSwic2lkIjoic2Vzc18zOHczUHFac2xOWDFBZ0NVOHFNRTNzZEpQenoiLCJzdHMiOiJhY3RpdmUiLCJzdWIiOiJ1c2VyXzM4dnljVHQ1ZWVYZ2RscnpRRGxrQjE1UnBNZiIsInYiOjJ9.DJNYFsTRKN4i_mmfOWvfJJnXN-Z4lgrO33DbwT8ypLJtxk9ldkHAi9E9kuMr4SKEnlGZ1eTqdr6bMHAK9JhkjjAhPhuIPivv9i6Cb_iTIGlF3reGVdBZszBDA981E1ZL6PpnoiDSWHm2o4-pJxDqpzT9bGQxmpt3Pm3HltAk1jblgjx47YFmtPQtAA8bFvscPwIZZT7oj0WjMho2it_NfHNsj7S3hGqTYZfvLLDprWQjCjI5tn99sQPVaXjYLgHbkMqpsg1oLftCZurkXvWFhiWYSVRsp3ZeEidPm2xlzjlE6kKnRZYahuH8YBhEto1PXqb9YfUZJ-ZRENx4p0SFZw
Content-Type: application/json

{
  "title": "Testing Clerk APIs without React",
  "category": "TECH",
  "content": "This article explains how to get Clerk JWT for REST clients."
}



### Read all active articles
GET http://localhost:4000/user-api/articles
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18zOHFQUlJ1b014RGJPWXdNZjJ1blZNYmhBcjQiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjUxNzMiLCJleHAiOjE3Njk2OTc1NjcsImZ2YSI6WzMsLTFdLCJpYXQiOjE3Njk2OTc1MDcsImlzcyI6Imh0dHBzOi8vcHJvbW90ZWQtZG9lLTQ4LmNsZXJrLmFjY291bnRzLmRldiIsIm5iZiI6MTc2OTY5NzQ5Nywic2lkIjoic2Vzc18zOHc0T240WVJPZk9OSFVFUkxleE4zMVVwMkkiLCJzdHMiOiJhY3RpdmUiLCJzdWIiOiJ1c2VyXzM4dnl4dFpYYVFBMDBtb2t5YXNDc2Y4dnFwUCIsInYiOjJ9.Mdu9ZI-3SOJgFNkJlJVIkWGb7zqn6DILB7BmNhoAoBVxzlRwHC9DnCZiPcORlVShqgwVuY_Zi9HVXL0prb56_gCRE92UGhaWwh7h3aM6m0HAEw1kjNw9i6TeXwlAVMyjyL42nh3LKHOXLoBkiiLJUP5q7hPcTOrE3Ei7vW_un54NY1FxE9F4l5NmhrZ1eroDkQNRfTr1hluACjJgN4dJnLBBl4cy4BW24O4edKD0dIhou3o7W99iok9ndqCCKswHw6tyS7J5SvNmYcSWWpBd4fmTu7IkVQstTAqzDrukgSM8JPNmW2YZf6ypop7f8uLGsw1s0s5XLGnY3QVeZCenhQ




### Add comment to an article (User)
PUT http://localhost:4000/user-api/comment/697b6e283f356a4d1c99d8e3
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18zOGhpNHVEbVZCVFpJZGlZU0FWR3JVSHkyT3AiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjUxNzMiLCJleHAiOjE3Njk1OTAyMzEsImZ2YSI6WzAsLTFdLCJpYXQiOjE3Njk1OTAxNzEsImlzcyI6Imh0dHBzOi8vc2V0LWtpbmdmaXNoLTgxLmNsZXJrLmFjY291bnRzLmRldiIsIm5iZiI6MTc2OTU5MDE2MSwic2lkIjoic2Vzc18zOHNaSnNZT3JrZWtZZHc3Y0lRd0piSnFZYWsiLCJzdHMiOiJhY3RpdmUiLCJzdWIiOiJ1c2VyXzM4cUphT2psdm5KcXRiR2R1ZjN0YjdwYk5UVSIsInYiOjJ9.O-3KKLBB2lWXOgXNXMA_9gCA_VnwHsIuaBqpyCmpxtWuRry-ysiSUItFF4fq5zz1ZpJKd9i4Z_G6xXZw-rFzVgUfoAflfl-VQ4EjE3NbTlIkgMdiaZrKEzRL1821RHPUi9_DmV1mW768cvis-na1zTNWfzSobS4pbARC9hzYqCHccWZMl66Wht95VhSe1008mx_er7dGZw6YBY5DR68BwaVfKV6POFiJfBzQh6uEWXMjKFVJ-bDqVtAr35uFPtlO5_xzDqwtcQv5Z2hlB-8oAvHlWrplBD9i-LRzKnVLnC46nOALqvunFRTI_eXHmvUWikizHbSkvRh2Hyg4G_8j_A
Content-Type: application/json

{
  "comment": "This article explains Clerk integration very clearly "
}





### Soft Delete Article (AUTHOR only)
PUT http://localhost:4000/author-api/articles/697b6e283f356a4d1c99d8e3
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18zOHFQUlJ1b014RGJPWXdNZjJ1blZNYmhBcjQiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjUxNzMiLCJleHAiOjE3NzAwNDE1ODMsImZ2YSI6WzE2LC0xXSwiaWF0IjoxNzcwMDQxNTIzLCJpc3MiOiJodHRwczovL3Byb21vdGVkLWRvZS00OC5jbGVyay5hY2NvdW50cy5kZXYiLCJuYmYiOjE3NzAwNDE1MTMsInNpZCI6InNlc3NfMzk3SUJrOFFhOEpjUVQ5MkRCNk56T3U1Yk1SIiwic3RzIjoiYWN0aXZlIiwic3ViIjoidXNlcl8zOHZ5Y1R0NWVlWGdkbHJ6UURsa0IxNVJwTWYiLCJ2IjoyfQ.qSdd5FO0UNOcK7ATiDRIL0ShHtoxuzixcUe53txamqHi5YAGtE97KGIswD8hxLqCjDlzH98uri85mIan1IJyYCNOGs4AAA5V-V1WPkpFjLC5Kmc7HMWvw6a-ra4Fbo2F1eSkem7N4YX_CLyJF_Vr0UXvin-P6ScHehnWKvfLjC5V2aaIxO92HN1_k3KlS5keYr3SUG2gNTr0b8ricsy0LHQuibiMV78GpYP8kj6l8XE_MNpRz1jpcnmxJTV4ZjlfSga45DHbcoIJ172MuhSwplcXzTTHkCsIR8s-JyXJt2taVcPro8ZktVGqIsorjUmGosoFKqbSz-jA_kwBNXpCOw
Content-Type: application/json




### Read articles by Author
GET http://localhost:4000/author-api/articles
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18zOHFQUlJ1b014RGJPWXdNZjJ1blZNYmhBcjQiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjUxNzMiLCJleHAiOjE3NzAwNDEwNjQsImZ2YSI6WzcsLTFdLCJpYXQiOjE3NzAwNDEwMDQsImlzcyI6Imh0dHBzOi8vcHJvbW90ZWQtZG9lLTQ4LmNsZXJrLmFjY291bnRzLmRldiIsIm5iZiI6MTc3MDA0MDk5NCwic2lkIjoic2Vzc18zOTdJQms4UWE4SmNRVDkyREI2TnpPdTViTVIiLCJzdHMiOiJhY3RpdmUiLCJzdWIiOiJ1c2VyXzM4dnljVHQ1ZWVYZ2RscnpRRGxrQjE1UnBNZiIsInYiOjJ9.Jh0VKSxMVMQiZ5zcFS3lKfG3UXcZq194fRoEu6bYizs8WjNNhjrlTZHR-8MKsDJH1cJM0EJe01UU92Jrbv3aKP6MQb01XoUtFjka4pjKUtuP4Sl265sZsD3BJXy-IF7oIwB_rg6leQdWkrHu0Vem--Ob2NdoOkMEsPxVOdpIkiT-wJvtE1Eyoh4n2D3gOZHAZWwNMxCn-Ll1C_VDPt-jmcaMRspnlS10fbU_1a_pcDbiCv__KOX6cYrGBf6abSZJI4XuLh_NWV9uxr3nufza8frWBBWCyfrPtyu_Z6L19eCtaSztxMNSjIKwkuSD5dqNPKn3Wrd4yUDG28d3Xb5ICQ




### edit article by author
PUT http://localhost:4000/author-api/articles/697b6e283f356a4d1c99d8e3/edit
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18zOHFQUlJ1b014RGJPWXdNZjJ1blZNYmhBcjQiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjUxNzMiLCJleHAiOjE3NzAwNDIwNjEsImZ2YSI6WzI0LC0xXSwiaWF0IjoxNzcwMDQyMDAxLCJpc3MiOiJodHRwczovL3Byb21vdGVkLWRvZS00OC5jbGVyay5hY2NvdW50cy5kZXYiLCJuYmYiOjE3NzAwNDE5OTEsInNpZCI6InNlc3NfMzk3SUJrOFFhOEpjUVQ5MkRCNk56T3U1Yk1SIiwic3RzIjoiYWN0aXZlIiwic3ViIjoidXNlcl8zOHZ5Y1R0NWVlWGdkbHJ6UURsa0IxNVJwTWYiLCJ2IjoyfQ.sheuzy0AByvSDUyFHtpprPxLe0e8Dmqh6Mu6D__2tBiXrNRHcU9zEu4uRpckUzKCyK-KtK7Hr-sLQWbxrMi_BeVMxdSDz3d2K0-dUxQNwLVCkXwMUZll1ztJSzQl1SNXOB2RqYSDgXcNpk73a7b9boH_iGqvnngV8uAqxCHl5XGfKoPJ_OSTbxY-VyH6a8Jn_mcA2HkQNiNJVbA8VuXNKc21fyNg6TkR3_4ZTKojD9ql5OuVXDEUHjC3i2fcPMlU8YESqDi0ANkY22ykXpW0mY9KhdUZDMg-Xx3wdUijTk8Pb9MYn6xBHMx0i7MaL6B4WfLHuMrX9Wl2J6Srb-wQew
Content-Type: application/json

{
  "title":"updated title",
  "content": "updated content "
}
